# Generated by Django 6.0.1 on 2026-01-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('industry', models.CharField(max_length=50)),
                ('formation', models.CharField(blank=True, choices=[('gmp', 'Formation GMP'), ('haccp', 'Formation HACCP'), ('reach', 'Formation REACH & CLP'), ('cosmetique', 'Réglementation Cosmétique'), ('webinaire', 'Webinaire Interactif'), ('classe-virtuelle', 'Classe Virtuelle'), ('sur-mesure', 'Formation Sur Mesure')], max_length=50)),
                ('session_date', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
